# Learning basic Pandas
- Used for data analysis

## Import pandas

In [2]:
import pandas as pd

## Dataframe
A dataframe is a table. A table consists of rows and columns. Each row and column pair identifies one cell (an entry)

When declaring a dataframe, we use a dictionary where key is the column names, and the values are list of entries in that column (from top to bottom). The lists are of equal length. We identify the rows with index-values, and the column with its names.

In [ ]:
diary = pd.DataFrame({'Milk':[20,10], 'Butter':[10,10], 'Yoghurt':[5,3]})

#write the name of your new dataframe to display it:
diary

   Milk  Butter  Yoghurt
0    20      10        5
1    10      10        3

We can see that the rows are identified by an index-value. We can also give these rows names. We do this after declaring our dictionary in the constructor and use 'Index'. 'Index' is the list of our row lables. I like to think of the *index* parameter as a column and the corresponding list as values down that column (with the row labels/names).

In [7]:
diary = pd.DataFrame({'Milk':[20,10], 'Butter':[10,10], 'Yoghurt':[5,3]}, index=['Family 1','Family 2'])
diary

          Milk  Butter  Yoghurt
Family 1    20      10        5
Family 2    10      10        3